### ISSUE TITLE
Adjusting image size in the pages

### ISSUE THREAD

**Issue by alterat** [HubRise/website#383]
Hi @antmonnier! While working on Lightspeed, I've come across an issue with images. Here, the embedded image is too large for the page.

<img width="936" alt="Screenshot 2021-07-17 at 10 01 06" src="https://user-images.githubusercontent.com/19559470/126030560-40e3e741-5ce8-437b-a5f8-1e9bba37d0ab.png">

Is there a way to specify how wide an image will look like in the page from the markdown source?
Ideally, I'm looking for something similar to:

```
![Alt text for the image](image-path.png){width=50%}
```
where the width can be expressed as a percentage of the pageview.

As a possible alternative, I tried to use plain html, but the "width" attribute does not seem to have an effect.

I tried:
- `<img src="../images/image-path.png" width="500px"/>`
- `<img src="../images/image-path.png" width="500"/>`

Any suggestions?

**Comment by antmonnier** [comment]
Hi @albert9168 

The migration to Next.js fixed this issue. Images now display at their natural size, provided that the filename contains the `-2x-` magic string for 2x resolution captures.

See for example: https://www.hubrise.com/apps/orderline/manage-orders#receipts
While the image of the receipt is 866px wide, it displays at half that because of the filename `030-2x-receipt-example.png`.

Of course, you don't lose the benefit of the extra pixels! This image will look sharp on a 2x display.

**Comment by antmonnier** [comment]
I've actually renamed the name of the image in the Lightspeed documentation:

**Before** - `007-lightspeed-system-choice.png`:

![image](https://github.com/HubRise/website/assets/5095197/0b3a064a-09bf-410f-98c2-42361120684a)

**After** - `007-2x-lightspeed-system-choice.png`:

![image](https://github.com/HubRise/website/assets/5095197/5a522aee-b216-4901-ad1f-cecdf68ca964)

**Comment by janaina-wittner** [comment]
For info both, the use of 2x is also documented here: https://www.hubrise.com/contributing/screenshots-guide#naming-convention

**Comment by albert9168** [comment]
Thank you both for the update!

@antmonnier can you clarify what happens if I don't include the `2x` magic string in the filename?
Does my image display correctly on my display (1280x800) but twice its normal size on a 4k screen?
