### ISSUE TITLE
Documentation layout: add support for inline images

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#67]
This markdown:
![image](https://user-images.githubusercontent.com/5095197/74520565-1ea28c00-4f18-11ea-9b12-56e81b98db2c.png)

Currently renders like this:
![image](https://user-images.githubusercontent.com/5095197/74520599-30842f00-4f18-11ea-91de-ba30c8f4421a.png)

The cross icon should be inlined instead of being rendered as a block.

**Comment by Ozerich** [comment]
I suggest to use SVG as inline images.
It's hard to correctly handle common images (png, jpg) as inline, because we have several plugins which have impact on images. Also images can have any sizes.
On the other hand, it's very handy to specify correct sizes for svg images by ourself
For example:

![image](https://user-images.githubusercontent.com/406041/74744024-89362d80-5272-11ea-97f7-120efbaa7fa1.png)
![image](https://user-images.githubusercontent.com/406041/74743936-5ab85280-5272-11ea-9b9c-38d8706c2d35.png)

**Comment by antmonnier** [comment]
Ok good idea, however it might happen that the contributor does not have the SVG version (or cannot easily create it). In this situation, is there a workaround to use a JPG/PNG?

**Comment by antmonnier** [comment]
@Ozerich Reminder about the above comment

**Comment by Ozerich** [comment]
> Ok good idea, however it might happen that the contributor does not have the SVG version (or cannot easily create it). In this situation, is there a workaround to use a JPG/PNG?

Yes, I've created PR (#74) with workaround
